"use client";

import { useEffect, useMemo } from "react";
import { COUNTRY_CODES } from "@/types/profile";
import { useLanguage, type VivaTripLocale } from "@/components/i18n/language-provider";

type Row = [string, string, string];
const rows: Row[] = [
  ["Conta","Account","Cuenta"],["Plano & cobrança","Plan & billing","Plan y facturación"],["O VivaTrip ainda está em fase de produto. Nenhuma cobrança automática está ativa nesta versão.","VivaTrip is still in product development. No automatic billing is active in this version.","VivaTrip aún está en fase de producto. No hay cobros automáticos activos en esta versión."],["Plano atual","Current plan","Plan actual"],["Organize viagens, perfil, roteiro e pré-viagem enquanto os recursos premium são preparados.","Organize trips, profile, itinerary and pre-trip while premium features are being prepared.","Organiza viajes, perfil, itinerario y previaje mientras se preparan las funciones premium."],["/ mês","/ month","/ mes"],["Premium em preparação","Premium in development","Premium en preparación"],["Ver planos planejados","View planned plans","Ver planes previstos"],
  ["Transparência","Transparency","Transparencia"],["Política de afiliados.","Affiliate disclosure.","Política de afiliados."],["Resultados e publicidade","Results and advertising","Resultados y publicidad"],["Tarifas","Fares","Tarifas"],
  ["Economize acompanhando","Save by tracking","Ahorra siguiendo"],["Salve as rotas que quer acompanhar. O VivaTrip só mostrará tarifas quando houver uma fonte real conectada — sem preços inventados.","Save the routes you want to track. VivaTrip will only show fares when a real data source is connected — no invented prices.","Guarda las rutas que quieres seguir. VivaTrip solo mostrará tarifas cuando haya una fuente real conectada, sin precios inventados."],
  ["Inspiração","Inspiration","Inspiración"],["Explore seu próximo destino","Explore your next destination","Explora tu próximo destino"],["Pesquise países e cidades, descubra destinos visualmente e leve sua escolha direto para o planejamento da viagem.","Search countries and cities, discover destinations visually and take your choice straight into trip planning.","Busca países y ciudades, descubre destinos visualmente y lleva tu elección directamente a la planificación del viaje."],["Fotos dos destinos em destaque: Unsplash. Requisitos de entrada variam conforme passaporte, residência, destino e datas; confirme sempre em fontes oficiais.","Featured destination photos: Unsplash. Entry requirements vary by passport, residence, destination and dates; always confirm with official sources.","Fotos de destinos destacados: Unsplash. Los requisitos de entrada varían según pasaporte, residencia, destino y fechas; confirma siempre en fuentes oficiales."],
  ["Organização de recompensas","Rewards organization","Organización de recompensas"],["Milhas & pontos","Miles & points","Millas y puntos"],["Central informativa para organizar programas, saldos e vencimentos. O VivaTrip não vende produtos financeiros nem recomenda contratação de cartões.","Information hub for organizing programs, balances and expiration dates. VivaTrip does not sell financial products or recommend signing up for cards.","Centro informativo para organizar programas, saldos y vencimientos. VivaTrip no vende productos financieros ni recomienda contratar tarjetas."],["Programas","Programs","Programas"],["Saldos em um só lugar","Balances in one place","Saldos en un solo lugar"],["Validade","Expiration","Vencimiento"],["Evite expirações","Avoid expirations","Evita vencimientos"],["Transferências","Transfers","Transferencias"],["Parceiros","Partners","Socios"],
  ["Ofertas verificadas, quando disponíveis.","Verified deals, when available.","Ofertas verificadas, cuando estén disponibles."],["Os valores ilustrativos da página inicial não representam disponibilidade ao vivo. Esta área será alimentada apenas por um provedor de preços real.","Illustrative prices on the home page do not represent live availability. This area will only be powered by a real pricing provider.","Los valores ilustrativos de la página inicial no representan disponibilidad en vivo. Esta área solo se alimentará de un proveedor real de precios."],["Nenhuma oferta ao vivo conectada","No live deals connected","No hay ofertas en vivo conectadas"],["Explorar destinos","Explore destinations","Explorar destinos"],
  ["Planos","Plans","Planes"],["Planeje primeiro. Assine quando fizer sentido.","Plan first. Subscribe when it makes sense.","Planifica primero. Suscríbete cuando tenga sentido."],["Grátis","Free","Gratis"],["Explorar","Explore","Explorar"],["Organização básica de viagens e perfil.","Basic trip and profile organization.","Organización básica de viajes y perfil."],["Começar","Get started","Comenzar"],["Futuro plano","Future plan","Plan futuro"],["Em breve","Coming soon","Próximamente"],
  ["Seus dados, com clareza.","Your data, clearly explained.","Tus datos, con claridad."],["Dados que você fornece","Data you provide","Datos que proporcionas"],["Serviços de terceiros","Third-party services","Servicios de terceros"],["Controle","Control","Control"],
  ["Busca de viagens","Trip search","Búsqueda de viajes"],["Compare com dados reais","Compare with real data","Compara con datos reales"],["Enquanto isso, planeje o destino","Meanwhile, plan your destination","Mientras tanto, planifica el destino"],["Você já pode criar a viagem, definir datas, hospedagem, interesses e gerar seu roteiro.","You can already create a trip, set dates, accommodation and interests, and generate your itinerary.","Ya puedes crear el viaje, definir fechas, alojamiento e intereses y generar tu itinerario."],
  ["Voltar ao início","Back to home","Volver al inicio"],["Seu jeito de viajar","Your way to travel","Tu forma de viajar"],["Perfil do viajante","Traveler profile","Perfil del viajero"],["Preferências que ajudam a VivaTrip a tornar cada viagem mais pessoal.","Preferences that help VivaTrip make every trip more personal.","Preferencias que ayudan a VivaTrip a hacer cada viaje más personal."],
  ["Seu mundo organizado","Your world, organized","Tu mundo organizado"],["Planeje, acompanhe e guarde cada detalhe das suas próximas experiências.","Plan, track and keep every detail of your upcoming experiences.","Planifica, sigue y guarda cada detalle de tus próximas experiencias."],["+ Nova viagem","+ New trip","+ Nuevo viaje"],["Sua próxima viagem começa aqui.","Your next trip starts here.","Tu próximo viaje empieza aquí."],["Criar minha primeira viagem","Create my first trip","Crear mi primer viaje"],["Novo destino","New destination","Nuevo destino"],["Crie sua viagem","Create your trip","Crea tu viaje"],["Comece pelo essencial. Você poderá ajustar tudo quando quiser.","Start with the essentials. You can adjust everything whenever you want.","Empieza por lo esencial. Podrás ajustar todo cuando quieras."],
  ["Viajantes","Travelers","Viajeros"],["Estilo","Style","Estilo"],["Estação aproximada","Approximate season","Estación aproximada"],["Não definido","Not set","Sin definir"],["A confirmar","To be confirmed","Por confirmar"],["Primavera","Spring","Primavera"],["Verão","Summer","Verano"],["Outono","Autumn","Otoño"],["Inverno","Winter","Invierno"],["Hospedagem","Accommodation","Alojamiento"],["Ainda não informada","Not provided yet","Aún no informado"],["Nenhum interesse selecionado.","No interests selected.","Ningún interés seleccionado."],
  ["Salvar rota","Save route","Guardar ruta"],["Novo alerta","New alert","Nueva alerta"],["Preço-alvo opcional","Optional target price","Precio objetivo opcional"],["Salvar alerta","Save alert","Guardar alerta"],["Seus alertas","Your alerts","Tus alertas"],["Data flexível","Flexible date","Fecha flexible"],["Sem preço-alvo","No target price","Sin precio objetivo"],["Aguardando integração","Awaiting integration","Esperando integración"],["Nenhum alerta salvo","No saved alerts","No hay alertas guardadas"],
  ["Informações pessoais","Personal information","Información personal"],["Os dados essenciais para personalizar sua experiência.","Essential data to personalize your experience.","Los datos esenciales para personalizar tu experiencia."],["Nome","Name","Nombre"],["Vinculado à sua conta VivaTrip.","Linked to your VivaTrip account.","Vinculado a tu cuenta VivaTrip."],["Nacionalidade","Nationality","Nacionalidad"],["País do passaporte","Passport country","País del pasaporte"],["País de residência","Country of residence","País de residencia"],["Preferências de viagem","Travel preferences","Preferencias de viaje"],["Conte como você gosta de descobrir o mundo.","Tell us how you like to discover the world.","Cuéntanos cómo te gusta descubrir el mundo."],["Aeroporto de origem","Home airport","Aeropuerto de origen"],["Configurações","Settings","Configuración"],["Idioma e moeda que você prefere usar.","Language and currency you prefer to use.","Idioma y moneda que prefieres usar."],["Idioma preferido","Preferred language","Idioma preferido"],["Moeda preferida","Preferred currency","Moneda preferida"],["Salvar perfil","Save profile","Guardar perfil"],["Perfil salvo com sucesso.","Profile saved successfully.","Perfil guardado correctamente."],["Carregando seu perfil…","Loading your profile…","Cargando tu perfil…"],
  ["Prepare o essencial antes de embarcar","Prepare the essentials before you go","Prepara lo esencial antes de viajar"],["Documentação","Documents","Documentación"],["Apps essenciais","Essential apps","Apps esenciales"],["Internet & eSIM","Internet & eSIM","Internet y eSIM"],["Dinheiro","Money","Dinero"],["Transporte","Transport","Transporte"],["Clima & mala","Weather & packing","Clima y equipaje"],["Seguro","Insurance","Seguro"],["Contatos & reservas","Contacts & bookings","Contactos y reservas"],["Salvar nota","Save note","Guardar nota"],["Editar nota","Edit note","Editar nota"],["+ Adicionar nota","+ Add note","+ Agregar nota"],
  ["Conhecendo seu destino…","Learning about your destination…","Conociendo tu destino…"],["Organizando seus dias…","Organizing your days…","Organizando tus días…"],["Considerando seus interesses…","Considering your interests…","Considerando tus intereses…"],["Adaptando à época da viagem…","Adapting to the travel season…","Adaptando a la época del viaje…"],["Montando seu roteiro…","Building your itinerary…","Armando tu itinerario…"],["Manhã","Morning","Mañana"],["Tarde","Afternoon","Tarde"],["Noite","Evening","Noche"],["Fim de noite","Late night","Noche tarde"],["Atração","Attraction","Atracción"],["Museu","Museum","Museo"],["Experiência","Experience","Experiencia"],["Descanso","Rest","Descanso"],["Outro","Other","Otro"],["Roteiro personalizado","Personalized itinerary","Itinerario personalizado"],["Título do roteiro","Itinerary title","Título del itinerario"],["Resumo","Summary","Resumen"],["Salvar roteiro","Save itinerary","Guardar itinerario"],["Seu roteiro VivaTrip","Your VivaTrip itinerary","Tu itinerario VivaTrip"],["Editar título e resumo","Edit title and summary","Editar título y resumen"],["Personalizado por você","Customized by you","Personalizado por ti"],["Gerar novo roteiro","Generate new itinerary","Generar nuevo itinerario"],["Salvando alteração…","Saving change…","Guardando cambio…"],["Dia","Day","Día"],["Título do dia","Day title","Título del día"],["Resumo do dia","Day summary","Resumen del día"],["Salvar dia","Save day","Guardar día"],["Editar dia","Edit day","Editar día"],["+ Adicionar atividade","+ Add activity","+ Agregar actividad"],["Período","Period","Período"],["Início","Start","Inicio"],["Fim","End","Fin"],["Categoria","Category","Categoría"],["Duração aproximada (min)","Approximate duration (min)","Duración aproximada (min)"],["Descrição","Description","Descripción"],["Local","Place","Lugar"],["Salvar atividade","Save activity","Guardar actividad"],
  ["IA ainda não configurada","AI not configured yet","IA aún no configurada"],["Não foi possível criar o roteiro. Tente novamente.","We couldn't create the itinerary. Please try again.","No pudimos crear el itinerario. Inténtalo de nuevo."],
];

const index: Record<string, Row> = {};
for (const row of rows) for (const text of row) index[text.trim()] = row;

function dynamic(value: string, locale: VivaTripLocale, countryMap: Map<string,string>) {
  const raw = value.trim(); const row = index[raw]; if (row) return row[locale === "pt" ? 0 : locale === "en" ? 1 : 2];
  if (countryMap.has(raw)) return countryMap.get(raw)!;
  let m = raw.match(/^Planeje sua viagem para (.+)$/); if (m) return locale === "en" ? `Plan your trip to ${m[1]}` : locale === "es" ? `Planea tu viaje a ${m[1]}` : raw;
  m = raw.match(/^Pré-viagem · (.+)$/); if (m) return locale === "en" ? `Pre-trip · ${m[1]}` : locale === "es" ? `Previaje · ${m[1]}` : raw;
  m = raw.match(/^(\d+) dias$/); if (m) return locale === "en" ? `${m[1]} days` : locale === "es" ? `${m[1]} días` : raw;
  m = raw.match(/^(\d+) de (\d+) itens concluídos$/); if (m) return locale === "en" ? `${m[1]} of ${m[2]} items completed` : locale === "es" ? `${m[1]} de ${m[2]} ítems completados` : raw;
  m = raw.match(/^(\d+)\/(\d+) concluídos$/); if (m) return locale === "en" ? `${m[1]}/${m[2]} completed` : locale === "es" ? `${m[1]}/${m[2]} completados` : raw;
  m = raw.match(/^Notas de (.+)$/); if (m) return locale === "en" ? `Notes for ${m[1]}` : locale === "es" ? `Notas de ${m[1]}` : raw;
  m = raw.match(/^Mover (.+) para cima$/); if (m) return locale === "en" ? `Move ${m[1]} up` : locale === "es" ? `Mover ${m[1]} hacia arriba` : raw;
  m = raw.match(/^Mover (.+) para baixo$/); if (m) return locale === "en" ? `Move ${m[1]} down` : locale === "es" ? `Mover ${m[1]} hacia abajo` : raw;
  return value;
}

export function SiteTranslationLayer() {
  const { locale, localeTag } = useLanguage();
  const countryMap = useMemo(() => {
    const target = new Intl.DisplayNames([localeTag], { type: "region" });
    const maps = ["pt-BR","en-US","es-AR"].map(tag => new Intl.DisplayNames([tag], { type: "region" }));
    const out = new Map<string,string>();
    for (const code of COUNTRY_CODES) for (const names of maps) { const source = names.of(code); if (source) out.set(source, target.of(code) || code); }
    return out;
  }, [localeTag]);

  useEffect(() => {
    const apply = (root: Node) => {
      const handleText = (node: Text) => { const p=node.parentElement; if(!p||p.closest("[data-no-translate]")||["SCRIPT","STYLE","CODE","PRE","TEXTAREA"].includes(p.tagName)) return; const v=node.nodeValue||""; if(!v.trim()) return; const t=dynamic(v.trim(),locale,countryMap); if(t!==v.trim()) node.nodeValue=v.replace(v.trim(),t); };
      const handleEl = (el: Element) => { if(el.closest("[data-no-translate]")) return; for(const a of ["placeholder","aria-label","title"]){const v=el.getAttribute(a); if(v){const t=dynamic(v,locale,countryMap); if(t!==v) el.setAttribute(a,t);}} };
      if(root.nodeType===Node.TEXT_NODE){handleText(root as Text);return;} if(!(root instanceof Element)&&root!==document.body)return; if(root instanceof Element)handleEl(root); const w=document.createTreeWalker(root,NodeFilter.SHOW_TEXT|NodeFilter.SHOW_ELEMENT); let n=w.nextNode(); while(n){if(n.nodeType===Node.TEXT_NODE)handleText(n as Text); else if(n instanceof Element)handleEl(n); n=w.nextNode();}
    };
    apply(document.body);
    const obs=new MutationObserver(ms=>{for(const m of ms){if(m.type==="characterData")apply(m.target); for(const n of m.addedNodes)apply(n);}}); obs.observe(document.body,{childList:true,subtree:true,characterData:true}); return()=>obs.disconnect();
  },[locale,countryMap]);
  return null;
}
